var mangaLinkGroupSize = 10;
var mangaList = `
http://kissmanga.com/Manga/Re-Monster
http://kissmanga.com/Manga/Death-March-kara-Hajimaru-Isekai-Kyousoukyoku
http://kissmanga.com/Manga/Goblin-Slayer
http://kissmanga.com/Manga/Goblin-Slayer-Side-Story-Year-One
http://kissmanga.com/Manga/Monster-Musume-no-Iru-Nichijou
http://kissmanga.com/Manga/Knights-Magic
http://kissmanga.com/Manga/Boku-no-Hero-Academia
http://kissmanga.com/Manga/Onepunch-Man
http://kissmanga.com/Manga/Onepunch-Man-ONE
http://kissmanga.com/Manga/Gate-Jietai-Kare-no-Chi-nite-Kaku-Tatakeri
http://kissmanga.com/Manga/Mushoku-Tensei-Isekai-Ittara-Honki-Dasu
http://kissmanga.com/Manga/Konjiki-no-Moji-Tsukai-Yuusha-Yonin-ni-Makikomareta-Unique-Cheat
http://kissmanga.com/Manga/The-New-Gate
http://kissmanga.com/Manga/Tate-no-Yuusha-no-Nariagari
http://kissmanga.com/Manga/Tsuyokute-New-Saga
http://kissmanga.com/Manga/Yakushoku-Distpiari-Gesellshaft-Blue
http://kissmanga.com/Manga/Kenja-no-Mago
http://kissmanga.com/Manga/World-Customize-Creator
http://kissmanga.com/Manga/Hachinan-tte-Sore-wa-Nai-Deshou
http://kissmanga.com/Manga/Arifureta-Shokugyou-de-Sekai-Saikyou
http://kissmanga.com/Manga/Isekai-de-Kuro-no-Iyashi-Te-tte-Yobarete-Imasu
http://kissmanga.com/Manga/Tsuki-ga-Michibiku-Isekai-Douchuu
http://kissmanga.com/Manga/Kekkon-Yubiwa-Monogatari
http://kissmanga.com/Manga/Nidome-no-Jinsei-wo-Isekai-de
http://kissmanga.com/Manga/Dungeon-Seeker
http://kissmanga.com/Manga/Tenseishichatta-yo-Iya-Gomen
http://kissmanga.com/Manga/Isekai-Maou-to-Shoukan-Shoujo-Dorei-Majutsu
http://kissmanga.com/Manga/Tensei-Shitara-Ken-deshita
http://kissmanga.com/Manga/Wortenia-Senki
http://kissmanga.com/Manga/Overlord
http://kissmanga.com/Manga/Kurogane-no-Ido
http://kissmanga.com/Manga/Meikyuu-Black-Company
http://kissmanga.com/Manga/LV999-no-Murabito
http://kissmanga.com/Manga/Final-Fantasy-Lost-Stranger
http://kissmanga.com/Manga/Tensei-Shitara-Slime-Datta-Ken
http://kissmanga.com/Manga/Tensei-Shitara-Slime-Datta-Ken-The-Ways-of-Strolling-in-the-Demon-Country
http://kissmanga.com/Manga/Gunota-ga-Mahou-Sekai-ni-Tensei-Shitara-Gendai-Heiki-de-Guntai-Harem-o-Tsukucchaimashita
http://kissmanga.com/Manga/Isekai-Meikyuu-de-Harem-o
http://kissmanga.com/Manga/Choujin-Koukousei-tachi-wa-Isekai-demo-Yoyuu-de-Ikinuku-you-desu
http://kissmanga.com/Manga/Gaikotsu-Kishi-sama-Tadaima-Isekai-e-o-Dekake-chuu
http://kissmanga.com/Manga/In-a-Different-World-with-a-Smartphone
http://kissmanga.com/Manga/Isekai-Cheat-Magician
http://kissmanga.com/Manga/Isekai-Mahou-wa-Okureteru
http://kissmanga.com/Manga/Isekai-Shihai-no-Skill-Taker-Zero-kara-Hajimeru-Dorei-Harem
http://kissmanga.com/Manga/Makikomarete-Isekai-Teni-suru-Yatsu-wa-Taitei-Cheat
http://kissmanga.com/Manga/Isekai-Yakkyoku
http://kissmanga.com/Manga/Isekai-wo-Seigyo-Mahou-de-Kirihirake
http://kissmanga.com/Manga/Isekai-ni-Kita-Mitai-dakedo-Ikanisureba-Yoi-no-Darou
http://kissmanga.com/Manga/Ore-to-Kawazu-san-no-Isekai-Hourouki
http://kissmanga.com/Manga/Isekai-Izakaya-Nobu
http://kissmanga.com/Manga/Isekai-Goumon-Hime
http://kissmanga.com/Manga/Isekai-desu-ga-Mamono-Saibai-shiteimasu
http://kissmanga.com/Manga/Isekai-de-Skill-wo-Kaitai-shitara-Cheat-na-Yome-ga-Zoushoku-Shimashita-Gainen-Kousa-no-Structure
http://kissmanga.com/Manga/Kou-1-Desu-ga-Isekai-de-Joushu-Hajimemashita
http://kissmanga.com/Manga/Yankee-Wa-Isekai-De-Seirei-Ni-Aisaremasu
http://kissmanga.com/Manga/World-Teacher-Isekaishiki-Kyouiku-Agent
http://kissmanga.com/Manga/Tondemo-Skill-de-Isekai-Hourou-Meshi
http://kissmanga.com/Manga/Takarakuji-de-40-oku-Atattandakedo-Isekai-ni-Ijuu-Suru
http://kissmanga.com/Manga/Golem-Hearts
http://kissmanga.com/Manga/Dungeon-ni-Deai-o-Motomeru-no-wa-Machigatte-Iru-Darou-ka
http://kissmanga.com/Manga/Isekai-Tensei-Soudouki
http://kissmanga.com/Manga/Isekai-Nonbiri-Nouka
http://kissmanga.com/Manga/Jui-san-no-Oshigoto-in-Isekai
http://kissmanga.com/Manga/Sozai-Saishuka-no-Isekai-Ryokouki
http://kissmanga.com/Manga/Monster-no-Goshujin-sama
http://kissmanga.com/Manga/Kuro-no-Shoukanshi
http://kissmanga.com/Manga/Enen-no-Shouboutai
http://kissmanga.com/Manga/Dungeon-Meshi
http://kissmanga.com/Manga/While-Killing-Slimes-for-300-Years--I-Became-the-MAX-Level-Unknowingly--Novel-
http://kissmanga.com/Manga/Shinju-no-Nectar
http://kissmanga.com/Manga/Matano-Okoshiwo
http://kissmanga.com/Manga/Manuke-na-FPS-Player-ga-Isekai-e-Ochita-Baai
http://kissmanga.com/Manga/Yuragi-sou-no-Yuuna-san
http://kissmanga.com/Manga/Isekai-Shokudou
http://kissmanga.com/Manga/Goblin-Is-Very-Strong
http://kissmanga.com/Manga/Isekai-Kenkokuki
http://kissmanga.com/Manga/Isekai-ni-Tobasareta-Ossan-wa-Doko-e-Iku
http://kissmanga.com/Manga/Isekai-Ryouridou
http://kissmanga.com/Manga/Isekai-Elf-no-Dorei-chan
http://kissmanga.com/Manga/Goodbye-Isekai-Tensei
http://kissmanga.com/Manga/Class-ga-Isekai-Shoukan-sareta-Naka-Ore-dake-Nokotta-n-desu-ga
http://kissmanga.com/Manga/Otome-Game-no-Hametsu-Flag-shika-nai-Akuyaku-Reijou-ni-Tensei-shite-shimatta
http://kissmanga.com/Manga/Grimore-x-Reverse-Tensei-Kishin-Roumantan
http://kissmanga.com/Manga/Reincarnated-as-a-Dragon-s-Egg-Let-s-Aim-to-be-the-Strongest
http://kissmanga.com/Manga/Jinrou-e-no-Tensei-Maou-no-Fukukan
http://kissmanga.com/Manga/Tenseisha-wa-Cheat-o-Nozomanai
http://kissmanga.com/Manga/Seichou-Cheat-de-Nandemo-Dekiru-you-ni-Natta-ga--Mushoku-dake-wa-Yamerarenai-you-desu
http://kissmanga.com/Manga/Sekkaku-Cheat-wo-Moratte-Isekai-ni-Teni-shita-n-dakara--Suki-na-you-ni-Ikitemitai
http://kissmanga.com/Manga/Moto-Saikyou-no-Kenshi-wa-Isekai-Mahou-ni-Akogareru
http://kissmanga.com/Manga/Elf-Yome-to-Hajimeru-Isekai-Ryoushu-Seikatsu
http://kissmanga.com/Manga/Isekai-no-Seikishi-Monogatari
http://kissmanga.com/Manga/M-M-G
http://kissmanga.com/Manga/Gokushufudou-The-Way-of-the-House-Husband
http://kissmanga.com/Manga/Elf-san-wa-Yaserarenai
http://kissmanga.com/Manga/NEET-dakedo-HELLO-WORK-ni-ittara-isekai-ni-tsuretekareta
http://kissmanga.com/Manga/Gacha-wo-Mawashite-Nakama-wo-Fuyasu-Saikyou-no-Bishoujo-Gundan-wo-Tsukuriagero
http://kissmanga.com/Manga/The-Feelings-of-a-Girl-with-Sanpaku-Eyes
http://kissmanga.com/Manga/Arafoo-Kenja-no-Isekai-Seikatsu-Nikki
http://kissmanga.com/Manga/Isekai-de-Kojiin-wo-Hiraitakedo-nazeka-Darehitori-Sudatou-to-Shinai-Ken
http://kissmanga.com/Manga/Isekai-ni-Tensei-Shitara-Zenra-ni-Sareta
http://kissmanga.com/Manga/Isekai-Omotenashi-Gohan
http://kissmanga.com/Manga/Seirei-tachi-no-Rakuen-to-Risou-no-Isekai-Seikatsu
http://kissmanga.com/Manga/Sokushi-Cheat-ga-Saikyou-Sugite-Isekai-no-Yatsura-ga-Marude-Aite-ni-Naranai-n-desu-ga
http://kissmanga.com/Manga/Tensei-Kizoku-no-Isekai-Boukenroku-Jichou-wo-Shiranai-Kamigami-no-Shito-
http://kissmanga.com/Manga/Isekai-Shoukan-wa-Nidome-Desu
`;
